### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by sirkrypt0** [eisen-oxid/thermit#2]
# Description

As a developer,  
I want to have a configured CI,  
in order to see that my code is integrating correctly.

# Acceptance Criteria

- [ ] A CI script exists
- [ ] The CI is running on pull requests
- [ ] The CI runs
  - [ ] A linter
  - [ ] All tests
  - [ ] `cargo check` to prove that the program compiles

**Comment by frcroth** [comment]
Something like #3

**Comment by sirkrypt0** [comment]
> Something like 13f1fda?

Looks good!

**Comment by frcroth** [comment]
Ok, dependent on #1
