### ISSUE TITLE
Deleting user that is in a room does not work due to ForeignKeyViolation

### ISSUE THREAD

**Issue by sirkrypt0** [eisen-oxid/thermit#37]
Deleting a user does not work anymore. The response is `Internal Server Error`. Debugging shows the DatabaseError is a `ForeignKeyViolation`. I assume this has to do with the `rooms_users` table.

## Steps to reproduce

1. Create a user. Note the userId
1. Create a room. Note the roomId
1. Add the user to the room.
1. Delete the user.
1. Note the "Internal Server Error" response.

## Expected behavior

The user is deleted correctly. The `rooms_users` connection get cleaned up as well.

**Comment by frcroth** [comment]
Yes yes `DELETE CASCADE`

**Comment by frcroth** [comment]
@sirkrypt0 By the way, do you want to create a bug issue template? Looks like you already use one.

**Comment by sirkrypt0** [comment]
> @sirkrypt0 By the way, do you want to create a bug issue template? Looks like you already use one.

Yes, good idea! See #40
