### ISSUE TITLE
Add Room model

### ISSUE THREAD

**Issue by frcroth** [eisen-oxid/thermit#8]

**Comment by frcroth** [comment]
@sirkrypt0 For whom are the good first issue labels?

**Comment by sirkrypt0** [comment]
> @sirkrypt0 For whom are the good first issue labels?

There might be additional contributors joining soon ;)

**Comment by frcroth** [comment]
@sirkrypt0 What exactly should the model be able to do?

**Comment by sirkrypt0** [comment]
> @sirkrypt0 What exactly should the model be able to do?

Should have the normal CRUD options. Creating a room might be with a given list of users that should belong to the room.
